Repository wuespace/telestion-project-daedalus2, pull requests merged in 2021-06, with the labels that each got.

#63 Update to telestion-client v0.15
  client/package-lock.json
  client/package.json
  client/src/model/spectrum-color.ts
  client/src/widgets/current-values-widget/components/overflow-fix.tsx
  client/src/widgets/current-values-widget/hooks/use-live-data.ts
  client/src/widgets/current-values-widget/widget.tsx
  client/src/widgets/hooks/index.ts
  client/src/widgets/hooks/use-dark-color-scheme.ts
  client/src/widgets/hooks/use-spectrum-color.ts
  client/src/widgets/pgraph-widget/components/pgraph.tsx
  client/src/widgets/pgraph-widget/model/chart-connection.ts
Labels: :tulip: enhancement, dependencies, javascript

#75 feat: Add new daedalus.xml mavlink messages
  definitions/daedalus.xml
Labels: :closed_book: documentation, :tulip: enhancement

#118 feat(widget): Add note widget
  client/src/model/dashboards/current-values-dashboard.ts
  client/src/model/dashboards/graph-dashboard.ts
  client/src/model/dashboards/index.ts
  client/src/model/dashboards/notes-dashboard.ts
  client/src/model/user-config.ts
  client/src/widgets/index.ts
  client/src/widgets/note-widget/config-controls.tsx
  client/src/widgets/note-widget/index.ts
  client/src/widgets/note-widget/model.ts
  client/src/widgets/note-widget/widget.tsx
Labels: :tulip: enhancement, javascript
